#!/usr/bin/env bash

COMPOSE="docker-compose"

if [ $# -gt 0 ]; then
    if [ "$1" == "run" ]; then
        shift 1
        $COMPOSE run ionic $@
    elif [ "$1" == "ionic" ]; then
        shift 1
        $COMPOSE exec ionic ionic $@
    elif [ "$1" == "yarn" ]; then
        shift 1
        $COMPOSE run --rm -w /var/www node yarn $@
    elif [ "$1" == "npm" ]; then
        shift 1
        $COMPOSE exec ionic npm $@
    elif [ "$1" == "nodenpm" ]; then
        shift 1
        $COMPOSE run --rm -w /app node npm $@
    elif [ "$1" == "node" ]; then
        shift 1
        $COMPOSE run --rm -w /app node node $@
    elif [ "$1" == "nodemon" ]; then
        shift 1
        $COMPOSE run --rm -w /app node nodemon $@
    elif [ "$1" == "tsc" ]; then
        shift 1
        $COMPOSE run --rm -w /app node tsc $@
    elif [ "$1" == "ng" ]; then
        $COMPOSE run ionic $@
    elif [ "$1" == "angular" ]; then
        shift 1
        $COMPOSE exec angular $@
    else
        $COMPOSE $@
    fi
else
    $COMPOSE ps
fi
